"""Reading a table from a file, and writing it as LaTeX.

Reading keeps every cell as text. Writing puts numbers in siunitx columns, aligned on the
decimal mark, exactly as they are written in the table, and everything else as text.
"""

import re
from pathlib import Path

from labharness.core.atomic import atomic_output
from labharness.core.tabular import DASHES, parse_decimal, read_rows
from labharness.modules.tables.table import Table, from_rows

EMPTY = "{---}"
_SPECIALS = {"&": r"\&", "%": r"\%", "#": r"\#", "_": r"\_", "{": r"\{", "}": r"\}"}
_MATH = re.compile(r"(\$[^$]*\$)")
_UNCERTAIN = re.compile(r"^\s*(\S+)\s*\+-\s*(\S+)\s*$")


def read_table(
    path: Path | str,
    delimiter: str | None = None,
    skip: int | None = None,
    skip_footer: int = 0,
    sheet: str | int | None = None,
    cells: str | None = None,
) -> Table:
    """Read a table (CSV, TSV, TXT, or .xlsx with the excel extra), every cell as text.

    The delimiter is worked out from the file unless given. ``skip`` is the number of lines
    above the header; left out, metadata lines an instrument writes there are skipped, with a
    warning. ``skip_footer`` drops lines at the end, such as totals. In a workbook, ``sheet``
    and ``cells`` choose the sheet and a range such as ``"A3:D20"``. For any other format,
    export it to CSV first, which every spreadsheet, database and instrument can do.
    """
    read = read_rows(
        path, delimiter=delimiter, skip=skip, skip_footer=skip_footer, sheet=sheet, cells=cells
    )
    return from_rows(read.headers, read.rows, source=Path(path).as_posix())


def write_table(table: Table, output: Path | str) -> Path:
    """Write the ``tabular`` of ``table`` to ``output``, for ``\\labtable`` in the manuscript.

    Only the tabular is written: the caption and the label belong in paper.tex.
    """
    columns = [_column_spec(table.column(header)) for header in table.headers]
    marks = {(row, column): letter for row, column, letter in table.marks}
    lines = [
        f"% Generated by LabHarness from {table.source or 'a table'}.",
        "% Do not edit: it is rewritten on every build.",
        r"\begin{threeparttable}",
        r"\begin{tabular}{" + " ".join(spec for spec, _ in columns) + "}",
        r"\toprule",
        " & ".join(
            f"{{{escape(header)}}}" if numeric else escape(header)
            for header, (_, numeric) in zip(table.headers, columns, strict=True)
        )
        + r" \\",
        r"\midrule",
    ]
    for index, row in enumerate(table.rows):
        if index in table.rules:
            lines.append(r"\midrule")
        cells = []
        for position, (cell, (_, numeric)) in enumerate(zip(row, columns, strict=True)):
            text = _cell(cell, numeric)
            letter = marks.get((index, position))
            if letter:
                text = f"{{{text}\\tnote{{{letter}}}}}" if numeric else f"{text}\\tnote{{{letter}}}"
            cells.append(text)
        lines.append(" & ".join(cells) + r" \\")
    lines += [r"\bottomrule", r"\end{tabular}"]
    if table.notes:
        lines.append(r"\begin{tablenotes}\footnotesize")
        lines += [rf"\item[{letter}] {escape(text)}" for letter, text in table.notes]
        lines.append(r"\end{tablenotes}")
    lines.append(r"\end{threeparttable}")

    output = Path(output)
    with atomic_output(output) as temporary:
        temporary.write_text("\n".join(lines) + "\n", encoding="utf-8", newline="\n")
    return output


def escape(text: str) -> str:
    """Escape LaTeX specials, leaving any $...$ maths the author wrote alone."""
    return "".join(
        part if part.startswith("$") else "".join(_SPECIALS.get(ch, ch) for ch in part)
        for part in _MATH.split(text.strip())
    )


def _number_text(cell: str) -> str | None:
    """A number cell in the form siunitx reads: decimal point, value +- error."""
    match = _UNCERTAIN.match(cell)
    if match:
        value, error = parse_decimal(match.group(1)), parse_decimal(match.group(2))
        if value is None or error is None:
            return None
        return f"{_plain(match.group(1))} +- {_plain(match.group(2))}"
    if parse_decimal(cell) is None:
        return None
    return _plain(cell)


def _plain(text: str) -> str:
    """The number exactly as written, only with a decimal point and an ASCII minus."""
    cleaned = text.strip().replace("−", "-").replace(" ", "")
    return cleaned.replace(",", ".") if "," in cleaned and "." not in cleaned else cleaned


def _column_spec(cells: list[str]) -> tuple[str, bool]:
    """An siunitx column if every filled cell is a number, else a text column."""
    numbers = []
    for cell in cells:
        if not cell.strip() or cell.strip() in DASHES:
            continue
        number = _number_text(cell)
        if number is None:
            return "l", False
        numbers.append(number)
    if not numbers:
        return "l", False

    integers = places = error_digits = 0
    negative = exponent = False
    for number in numbers:
        value, _, error = number.partition(" +- ")
        if "e" in value.lower() or "e" in error.lower():
            exponent = True
        negative = negative or value.startswith("-")
        whole, _, fraction = value.lstrip("+-").partition(".")
        integers = max(integers, len(whole))
        places = max(places, len(fraction))
        if error:
            error_digits = max(error_digits, len(error.replace(".", "").lstrip("0")) or 1)
    if exponent:
        return "S", True  # siunitx sizes a column with exponents on its own
    fmt = f"{'-' if negative else ''}{max(integers, 1)}.{places}"
    if error_digits:
        fmt += f"({error_digits})"
    return f"S[table-format={fmt}]", True


def _cell(cell: str, numeric: bool) -> str:
    if not cell.strip():
        return EMPTY
    if numeric:
        number = _number_text(cell)
        return number if number is not None else EMPTY
    return escape(cell)
