"""Protecting raw data: every file in ``data/`` is fingerprinted, and a change has to be accepted.

``labharness.lock`` records the SHA-256 of each data file. New files are welcome and are
registered on the next build. A registered file that changes, or disappears, is reported on
every build until a person runs ``labharness accept``, which records who accepted it, when, and
what it replaced. The build itself still runs: a correction must be possible, and visible.

The lock is plain TOML and belongs in version control, next to the data it protects.
"""

import getpass
import hashlib
import tomllib
from dataclasses import dataclass, field
from datetime import UTC, datetime
from pathlib import Path
from typing import Any

from labharness.core.atomic import atomic_output
from labharness.core.errors import LabHarnessError

LOCK_NAME = "labharness.lock"
DATA_FOLDER = "data"
TEXT_SUFFIXES = {".csv", ".txt", ".smi", ".tsv", ".dat", ".asc", ".mol", ".sdf", ".xy"}
HEADER = """\
# Generated by LabHarness: fingerprints of the raw data in data/.
# A changed file is reported until a person accepts it with: labharness accept <file>
# Keep this file in version control, next to the data.
"""


@dataclass(frozen=True)
class Fingerprint:
    sha256: str
    size: int
    lines: int | None

    def describe(self) -> str:
        return f"{self.lines} lines" if self.lines is not None else f"{self.size} bytes"


@dataclass(frozen=True)
class Change:
    path: str
    before: Fingerprint
    after: Fingerprint | None

    @property
    def message(self) -> str:
        if self.after is None:
            return f"{self.path} was removed since it was accepted"
        detail = f"{self.before.describe()} -> {self.after.describe()}"
        if self.before.describe() == self.after.describe():
            detail = "same size, different content"
        return f"{self.path} changed since it was accepted ({detail})"


@dataclass(frozen=True)
class DataReport:
    registered: tuple[str, ...] = ()
    changes: tuple[Change, ...] = field(default_factory=tuple)

    @property
    def clean(self) -> bool:
        return not self.changes


def fingerprint(path: Path) -> Fingerprint:
    return fingerprint_bytes(path.read_bytes(), text=path.suffix.lower() in TEXT_SUFFIXES)


def fingerprint_bytes(data: bytes, text: bool) -> Fingerprint:
    """The fingerprint of a file's content.

    Text is hashed with its line endings normalised: git on Windows turns LF into CRLF when it
    checks a file out, and the same measurements must not look changed on another machine.
    """
    if text:
        data = data.replace(b"\r\n", b"\n")
    lines = data.count(b"\n") + (0 if data.endswith(b"\n") or not data else 1)
    return Fingerprint(
        sha256=hashlib.sha256(data).hexdigest(),
        size=len(data),
        lines=lines if text else None,
    )


def data_files(root: Path) -> list[str]:
    """Every data file, as a path relative to the workspace.

    Skips hidden files and the ``~$`` lock files Office writes while a spreadsheet is open.
    """
    folder = root / DATA_FOLDER
    if not folder.is_dir():
        return []
    return sorted(
        path.relative_to(root).as_posix()
        for path in folder.rglob("*")
        if path.is_file()
        and not any(part.startswith((".", "~$")) for part in path.relative_to(folder).parts)
    )


def check_data(root: Path) -> DataReport:
    """Register new data files, and report the registered ones that changed or disappeared."""
    lock = _read(root)
    files = lock.setdefault("files", {})
    registered, changes = [], []

    present = data_files(root)
    for name in present:
        current = fingerprint(root / name)
        known = files.get(name)
        if known is None:
            files[name] = _entry(current)
            registered.append(name)
        elif known["sha256"] != current.sha256:
            changes.append(Change(name, _fingerprint(known), current))
    for name, known in sorted(files.items()):
        if name not in present:
            changes.append(Change(name, _fingerprint(known), None))

    if registered:
        _write(root, lock)
    return DataReport(registered=tuple(registered), changes=tuple(changes))


def accept(root: Path, names: list[str], by: str | None = None) -> list[Change]:
    """Accept changes to data files, recording who, when and what they replaced."""
    # First, so the files it registers are in the lock read just after.
    pending = {change.path: change for change in check_data(root).changes}
    lock = _read(root)
    files = lock.setdefault("files", {})
    history = lock.setdefault("history", [])
    accepted = []
    when = datetime.now(UTC).replace(microsecond=0).isoformat()
    who = by or getpass.getuser()

    for raw in names:
        name = _relative(root, raw)
        change = pending.get(name)
        if change is None:
            raise LabHarnessError(f"{name} has no change to accept")
        if change.after is None:
            del files[name]
        else:
            files[name] = _entry(change.after)
        history.append(
            {
                "file": name,
                "previous": change.before.sha256,
                "current": change.after.sha256 if change.after else "removed",
                "accepted": when,
                "by": who,
            }
        )
        accepted.append(change)

    _write(root, lock)
    return accepted


def _relative(root: Path, raw: str) -> str:
    path = Path(raw)
    absolute = (path if path.is_absolute() else Path.cwd() / path).resolve()
    try:
        return absolute.relative_to(root.resolve()).as_posix()
    except ValueError:
        return path.as_posix()


def _entry(current: Fingerprint) -> dict[str, object]:
    entry: dict[str, object] = {"sha256": current.sha256, "size": current.size}
    if current.lines is not None:
        entry["lines"] = current.lines
    return entry


def _fingerprint(entry: dict[str, object]) -> Fingerprint:
    lines = entry.get("lines")
    return Fingerprint(
        sha256=str(entry["sha256"]),
        size=int(str(entry.get("size", 0))),
        lines=int(str(lines)) if lines is not None else None,
    )


def _read(root: Path) -> dict[str, Any]:
    path = root / LOCK_NAME
    if not path.is_file():
        return {}
    try:
        return tomllib.loads(path.read_text(encoding="utf-8"))
    except tomllib.TOMLDecodeError as error:
        raise LabHarnessError(f"{path} is not valid TOML: {error}") from error


def _write(root: Path, lock: dict[str, Any]) -> None:
    lines = [HEADER]
    for name, entry in sorted(lock.get("files", {}).items()):
        lines.append(f'[files."{name}"]')
        lines += [f"{key} = {_toml(value)}" for key, value in entry.items()]
        lines.append("")
    for record in lock.get("history", []):
        lines.append("[[history]]")
        lines += [f"{key} = {_toml(value)}" for key, value in record.items()]
        lines.append("")
    with atomic_output(root / LOCK_NAME) as temporary:
        temporary.write_text("\n".join(lines).rstrip("\n") + "\n", encoding="utf-8", newline="\n")


def _toml(value: object) -> str:
    if isinstance(value, bool):
        return "true" if value else "false"
    if isinstance(value, int):
        return str(value)
    text = str(value).replace("\\", "\\\\").replace('"', '\\"')
    return f'"{text}"'
